name: React deploy artifact

env:
  CI: false

on:
  workflow_call:
    inputs:
      environment-name:
        required: false
        type: string
      environment-url:
        required: false
        type: string
      artifact-name:
        required: true
        type: string
      container-destination:
        required: true
        type: string
    secrets:
      CONTAINER_NAME:
        required: true
      CONTAINER_KEY:
        required: true
        
jobs:
  deploy-artifact:
    name: Deploy
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}
    runs-on: self-hosted
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ github.workspace }}/build
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: az storage blob upload-batch --source $GITHUB_WORKSPACE/build --destination '${{ inputs.container-destination }}' --account-name ${{ secrets.CONTAINER_NAME }} --account-key ${{ secrets.CONTAINER_KEY }} --overwrite
