name: React build artifact

on:
  workflow_call:
    inputs:
      dotenv-name:
        required: true
        type: string
      environment-name:
        required: false
        type: string
      environment-url:
        required: false
        type: string
      artifact-name:
        required: true
        type: string
      hook-before-build:
        required: false
        type: string
      
        
jobs:
  build-artifact:
    name: Build
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}
    runs-on: self-hosted
    steps:
      - name: Checkout code branch ${{ github.ref_name }}
        uses: actions/checkout@v3
      - name: Use Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependency
        run: npm i
      - name: Load dotenv file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          filenames: ${{ inputs.dotenv-name }}
      - name: Hook before build
        if: ${{ inputs.hook-before-build }}
        run: ${{ inputs.hook-before-build }}
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ github.workspace }}/build
          if-no-files-found: error 
